config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes
  get "/search", to: "recipes#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true
  validates :measure, presence: true
  validates :measure_type, presence: true
end

app/models/method_step.rb
class MethodStep < ApplicationRecord
  belongs_to :recipe

  validates :step, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, inverse_of: :recipe, dependent: :destroy
    has_many :method_steps, inverse_of: :recipe, dependent: :destroy

    accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :method_steps, reject_if: :all_blank, allow_destroy: true

    validates :name, length: { maximum: 100 }, presence: true
    validates :body, length: 1..1000, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @recipe.method_steps.build
  end


  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end 
  end

  def show
    set_recipe
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def search
    recipe = "%#{params[:recipe]}%"
    ingredient = "%#{params[:ingredient]}%"
    
    if params[:recipe].present? && params[:ingredient].present?
      @recipes = Recipe.joins(:ingredients).where("ingredients.name LIKE ?", ingredient).and(Recipe.where("recipes.name LIKE ?", recipe)).uniq
    elsif params[:recipe].present?
      @recipes = Recipe.where("recipes.name LIKE ?", recipe).uniq
    elsif params[:ingredient].present?
      @recipes = Recipe.joins(:ingredients).where("ingredients.name LIKE ?", ingredient).uniq
    else
      @recipes = Recipe.all.uniq
    end

    render :index
  end

  private
  def set_recipe
      @recipe = Recipe.find(params[:id])
  end

  def recipe_params
      params.require(:recipe).permit(
        :name,
        :body,
        ingredients_attributes: [
          :id,
          :name,
          :measure,
          :measure_type,
          :_destroy
        ],
        method_steps_attributes: [
          :id,
          :step,
          :_destroy
        ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes Book App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-around bd-highlight">
      <!-- <div class="container px-4 px-lg-5"> -->
        <div class="d-flex justify-content-start">
          <a class="navbar-brand" href="/">Recipe Book App</a>
        </div>
      <div class="d-flex justify-content-end">
        <%= link_to "Criar nova receita", new_recipe_path, class:"btn btn-primary btn-lg" %>
      </div>
    </nav>
    <div class="flex-1">
      <%= yield %>
    </div>

    <footer class="py-5 bg-dark">
      <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Gledson Strublic 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/partials/_search.html.erb
<form action="/search" class="form-inline d-inline">
    <input type="text" name="recipe" id="recipe" class="form-control mb-2 mr-sm-2" placeholder="Pesquise por Receita">
    <input type="text" name="ingredient" id="ingredient" class="form-control mb-2 mr-sm-4" placeholder="Pesquise por Ingrediente">
    <input type="submit" value="Pesquisar" class="btn btn-light mb-2 mr-sm-2">
</form>

app/views/recipes/_form.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><%= @recipe.id.present? ? "Receita: #{@recipe.name}" : "Nova receita" %></h3>
  </div>
  <div class="card-body">
    <%= form_with(model: @recipe, data: {
        controller: "nested-form",
        nested_form_wrapper_selector_value: '.nested-form-wrapper'
      }) do |form| %>
      
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="name">Nome da receita</label>
          <%= form.text_field :name, class: "form-control", placeholder: "Nome da receita", required: :true %>
        </div>

        <div class="col-md-4 mb-3">
          <label for="body">Descrição</label>
          <%= form.text_area :body, class: "form-control", placeholder: "Nome da receita", required: :true  %>
        </div>
      </div>

      <!-- Ingredients form -->
      <h5>Ingredientes</h5>

      <div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
        <template data-nested-form-target="template">
          <%= form.fields_for :ingredients, Ingredient.new, child_index: 'NEW_RECORD' do |ingredient_fields| %>
            <%= render "ingredient_form", f: ingredient_fields %>
          <% end %>
        </template>

        <%= form.fields_for :ingredients do |ingredient_fields| %>
          <%= render "ingredient_form", f: ingredient_fields %>
        <% end %>
        <div data-nested-form-target="target"></div>

        <div class="form-row">
          <div class="col-md-4 mb-3">
            <button type="button" data-action="nested-form#add">Add item</button>
          </div>
        </div>
      </div>
      <!-- end Ingredients form -->

      <!-- Method Steps form -->
      <h5>Modo de Preparo</h5>

      <template data-nested-form-target="template">
        <%= form.fields_for :method_steps, MethodStep.new, child_index: 'NEW_RECORD' do |method_step_fields| %>
          <%= render "method_step_form", f: method_step_fields %>
        <% end %>
      </template>

      <%= form.fields_for :method_steps do |method_step_fields| %>
        <%= render "method_step_form", f: method_step_fields %>
      <% end %>
      <div data-nested-form-target="target"></div>

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <button type="button" data-action="nested-form#add">Add item</button>
        </div>
      </div>
      <!-- end Method Steps form -->

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <%= form.submit %>
        </div>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <%= link_to "Voltar", root_path %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_ingredient_form.html.erb
<div class="nested-form-wrapper card-header" data-new-record="<%= f.object.new_record? %>">
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="name">Ingrediente</label>
            <%= f.text_field :name, class: "form-control", placeholder: "Ingrediente", required: true %>
        </div>

        <div class="col-md-2 mb-3">
            <label for="measure">Medida</label>
            <%= f.number_field :measure, class: "form-control", min: 0, placeholder: "Medida", required: true %>
        </div>

        <div class="col-md-4 mb-3">
            <label for="measure_type">Tipo de medida</label>
            <%= f.text_field :measure_type, class: "form-control", placeholder: "Tipo de medida", required: true %>
        </div>

        <div class="col-md-2 mb-3">
            <button type="button", class="btn btn-danger btn-bottom", title="Remover" data-action="nested-form#remove">X</button>
            <%= f.hidden_field :_destroy %>
        </div>
    </div>
</div>

app/views/recipes/_method_step_form.html.erb
<div class="nested-form-wrapper card-header" data-new-record="<%= f.object.new_record? %>">
    <div class="form-row">
        <div class="col-md-10 mb-3">
            <label for="name">Etapa</label>
            <%= f.text_field :step, class: "form-control", placeholder: "Etapa", required: true %>
        </div>

        <div class="col-md-2 mb-3">
            <button type="button", class="btn btn-danger btn-bottom", title="Remover" data-action="nested-forms#remove">X</button>
            <%= f.hidden_field :_destroy %>
        </div>
    </div>
</div>

app/views/recipes/edit.html.erb
<%= render "form" %>

app/views/recipes/index.html.erb
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Receitas</h1>
            <p class="lead fw-normal text-white-50 mb-0">Crie ou encontre uma receita</p>

            <%= render "partials/search" %>
        </div>
    </div>
</header>
<section class="py-5 p-4">
    <div class="text-center">
        <%= "Não possuimos nenhum receita cadastrada no momento." if @recipes.empty? %>
    </div>
    <div class="row">
        <% @recipes.each do |recipe| %>
            <div class="mb-3 col col-lg-2">
                <div class="card h-100">
                    <%= link_to recipe  do %>
                        <%= image_tag "receita_tradicional", class:"card-img-top" %>
                    <% end %>

                    <div class="card-body">
                        <h5 class="card-title font-weight-bold">
                            <%= recipe.name %>
                        </h5>
                        <p class="card-text">
                            <%= recipe.body %>
                        </p>
                    </div>

                    <!-- action buttons -->
                    <div class="card-footer">
                        <%= link_to recipe, {class: 'text-primary btn-sm text-decoration-none' }  do %>
                            VER
                        <% end %>
                        <%= link_to edit_recipe_path(recipe), {class: 'text-warning btn-sm text-decoration-none'} do %>
                            EDITAR
                        <% end %>
                        <%= link_to "DELETAR", recipe_path(recipe), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Tem certeza que deseja excluir este item?" },
                            class: 'text-danger btn-sm text-decoration-none' %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/recipes/new.html.erb
<%= render "form" %>

app/views/recipes/show.html.erb
<div class="card">
    <div class="card-header">
        <h1 class="card-title"><%= "#{@recipe.name.upcase}" %></h1>
    </div>

    <div class="card-body">        
        <div class="row">
            <%= image_tag "receita_tradicional", class:"img-recipe" %>
            
            <div class="col-md-12 mb-3">
                <h5 class="card-title font-weight-bold">Descrição</h5>
                <p><%= @recipe.body %></p>
            </div>
        </div>

        <!-- Ingredients form -->
        <h5 class="card-title font-weight-bold">Ingredientes</h5>

        <ul>
            <% @recipe.ingredients.each do |item| %>
                <li><%= item.measure %> <%= item.measure_type %>: <%= item.name %></li>
            <% end %>
        </ul>
        <!-- end Ingredients form -->

        <!-- Method Steps form -->
        <h5 class="card-title font-weight-bold">Modo de Preparo</h5>
        <ul>
            <% @recipe.method_steps.each do |item| %>
                <li><%= item.step %></li>
            <% end %>
        </ul>
        <!-- end Method Steps -->

        <div class="form-row">
            <div class="col-md-4 mb-3">
                <%= link_to "Voltar", root_path %>
            </div>
        </div>
    </div>
</div>